/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.i_comit.windows;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.JLabel;

/**
 * @author Khiem Luong <khiemluong@i-comit.com>
 */
public class DriveCheck extends javax.swing.JFrame {

    public static int driveState = 0;
    private URL fontFile = getClass().getResource("/polentical-neon.ttf");

    public DriveCheck(){
        initComponents();
        this.setBackground(new Color(0, 0, 0, (float)0.4));
        switch (driveState) {
            case 1:
                jLabel1.setText("i-ncript can only run");
                goWebsite(jLabel2, "within a ", "https://i-comit.com", "USB device", false);
//                Thread.sleep(5000);
//                this.dispose();
//                System.exit(0);
                break;
            case 2:
                jLabel1.setText("i-ncript must be in a");
                jLabel2.setText("folder named '-------'");

                break;
            case 3:
                goWebsite(jLabel1, "the folder with ", "https://i-comit.com/i-ncript/", "i-ncript", false);
                jLabel2.setText("must be placed at root");

                break;
        }
        new Thread(() -> {
            try {
                Thread.sleep(4000);
                this.dispose();
                System.exit(0);
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
        }).start();
    }

    public static final String goWebsite(JLabel website, final String leadingStr, final String url, String text, boolean changeColor) {
        if (changeColor) {
            website.setText("<html>"
                    + leadingStr + "<a style=\"text-decoration:none\" text=\"rgb(187,187,187)\" href=\"\">"
                    + text + "</a><span text=\"rgb(187,187,187)\" style=\"white-space: nowrap\"><font size=\"2\">" + "®" + "</font></span></html>");
        } else {
            website.setText("<html>" + leadingStr + "<a style=\"text-decoration:none\" href=\"\">" + text + "</a></html>");
        }
        if (!url.equals("")) {
            website.setCursor(new Cursor(Cursor.HAND_CURSOR));
            website.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    try {
                        Desktop.getDesktop().browse(new URI(url));
                    } catch (URISyntaxException | IOException ex) {
                        //It looks like there's a problem
                    }
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    if (changeColor) {
                        website.setText("<html>"
                                + leadingStr + "<a style=\"text-decoration:none\" text=\"rgb(107,107,107)\" href=\"\">"
                                + text + "</a><span text=\"rgb(107,107,107)\" style=\"white-space: nowrap\"><font size=\"2\">" + "®" + "</font></span></html>");
                    }
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    if (changeColor) {
                        website.setText("<html>"
                                + leadingStr + "<a style=\"text-decoration:none\" text=\"rgb(187,187,187)\" href=\"\">"
                                + text + "</a><span text=\"rgb(187,187,187)\" style=\"white-space: nowrap\"><font size=\"2\">" + "®" + "</font></span></html>");
                    }
                }
            });
        }
        return website.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("i-ncript™");
        setAlwaysOnTop(true);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/i-comiti.png")));
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(Statics.registerCustomFont(14, fontFile));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(Statics.registerCustomFont(14, fontFile));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JLabel jLabel1;
    protected static javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
