// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDirName() {
  return window['go']['main']['App']['CheckDirName']();
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function EncryptString(arg1) {
  return window['go']['main']['App']['EncryptString'](arg1);
}

export function GetAppPath() {
  return window['go']['main']['App']['GetAppPath']();
}

export function GetDirectoryStructure() {
  return window['go']['main']['App']['GetDirectoryStructure']();
}

export function GetRootFolder() {
  return window['go']['main']['App']['GetRootFolder']();
}

export function InitializeRootFolder() {
  return window['go']['main']['App']['InitializeRootFolder']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function MinimizeApp() {
  return window['go']['main']['App']['MinimizeApp']();
}

export function ResizeWindow(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeWindow'](arg1, arg2, arg3);
}
