// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildDirectoryFileTree(arg1:number):Promise<main.FileNode>;

export function CloseApp():Promise<void>;

export function DecryptFilesInDir():Promise<void>;

export function EncryptFilesInDir(arg1:number):Promise<boolean>;

export function FilesDragNDrop(arg1:Array<number>,arg2:string,arg3:string):Promise<void>;

export function InitializeRootFolder():Promise<void>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function MinimizeApp():Promise<void>;

export function ResizeWindow(arg1:number,arg2:number,arg3:boolean):Promise<void>;
