// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildDirectoryFileTree(arg1) {
  return window['go']['main']['App']['BuildDirectoryFileTree'](arg1);
}

export function CheckDirName() {
  return window['go']['main']['App']['CheckDirName']();
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function DecryptFilesInDir() {
  return window['go']['main']['App']['DecryptFilesInDir']();
}

export function EncryptFilesInDir(arg1) {
  return window['go']['main']['App']['EncryptFilesInDir'](arg1);
}

export function EncryptString(arg1) {
  return window['go']['main']['App']['EncryptString'](arg1);
}

export function InitializeRootFolder() {
  return window['go']['main']['App']['InitializeRootFolder']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function MinimizeApp() {
  return window['go']['main']['App']['MinimizeApp']();
}

export function ResizeWindow(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeWindow'](arg1, arg2, arg3);
}
