// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFilesInDir():Promise<void>;

export function EncryptFilesInDir(arg1:number):Promise<void>;
