// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DirectoryWatcher(arg1:boolean):Promise<void>;

export function EncryptString(arg1:string):Promise<string>;

export function GetDecryptedFiles(arg1:number):Promise<Array<string>>;

export function GetEncryptedFiles(arg1:number):Promise<Array<string>>;
