// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFilesInDir() {
  return window['go']['main']['Encryptor']['DecryptFilesInDir']();
}

export function EncryptFilesInDir(arg1) {
  return window['go']['main']['Encryptor']['EncryptFilesInDir'](arg1);
}
