// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EncryptString(arg1) {
  return window['go']['main']['Encryptr']['EncryptString'](arg1);
}

export function GetDecryptedFiles(arg1) {
  return window['go']['main']['Encryptr']['GetDecryptedFiles'](arg1);
}

export function GetEncryptedFiles(arg1) {
  return window['go']['main']['Encryptr']['GetEncryptedFiles'](arg1);
}
