// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateENCPFile(arg1, arg2) {
  return window['go']['main']['FileUtils']['AuthenticateENCPFile'](arg1, arg2);
}

export function CheckIfPathIsFile(arg1) {
  return window['go']['main']['FileUtils']['CheckIfPathIsFile'](arg1);
}

export function GetAppendedFileBytes(arg1) {
  return window['go']['main']['FileUtils']['GetAppendedFileBytes'](arg1);
}

export function MoveFilesToPath(arg1, arg2) {
  return window['go']['main']['FileUtils']['MoveFilesToPath'](arg1, arg2);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['FileUtils']['OpenDirectory'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['FileUtils']['OpenFile'](arg1);
}

export function PackFilesForENCP(arg1, arg2, arg3) {
  return window['go']['main']['FileUtils']['PackFilesForENCP'](arg1, arg2, arg3);
}

export function SaveLogEntries(arg1, arg2) {
  return window['go']['main']['FileUtils']['SaveLogEntries'](arg1, arg2);
}
