// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIfPathIsFile(arg1:string):Promise<boolean>;

export function FilesDragNDrop(arg1:Array<number>,arg2:string,arg3:number,arg4:string):Promise<void>;

export function MoveFilesToPath(arg1:Array<string>,arg2:string):Promise<void>;

export function SetIsInFileTask(arg1:boolean):Promise<boolean>;
