// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIfPathIsFile(arg1:string):Promise<boolean>;

export function GetAppendedFileBytes(arg1:string):Promise<void>;

export function MoveFilesToPath(arg1:Array<string>,arg2:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function PackFilesForENCP(arg1:Array<string>):Promise<void>;
