// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilesDragNDrop(arg1, arg2, arg3, arg4) {
  return window['go']['main']['FileUtils']['FilesDragNDrop'](arg1, arg2, arg3, arg4);
}

export function SetIsInFileTask(arg1) {
  return window['go']['main']['FileUtils']['SetIsInFileTask'](arg1);
}
