// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckKeyFileInCWD():Promise<string>;

export function CheckRootFolderInCWD():Promise<string>;

export function FindEncryptedDuplicates(arg1:number):Promise<Array<string>>;

export function GetAppPath():Promise<string>;

export function GetDirName():Promise<boolean>;

export function GetDirectoryFileCt(arg1:number):Promise<number>;

export function GetDirectoryPath(arg1:number):Promise<string>;

export function GetFileProperties(arg1:string):Promise<main.FileProperties>;

export function GetFileTreePath(arg1:number,arg2:string):Promise<string>;

export function GetFilesByType(arg1:number,arg2:boolean):Promise<Array<string>>;

export function GetFormattedAppDirSize():Promise<string>;

export function GetFormattedDirIndexSize(arg1:number):Promise<string>;

export function GetFormattedDriveSize():Promise<string>;

export function GetPercentOfDriveToAppDirSize():Promise<number>;

export function GetPercentOfDriveToDirIndexSize(arg1:number):Promise<number>;

export function GetRootDiskSpace():Promise<number>;

export function GetRootFolder():Promise<string>;

export function GetTotalDirSize(arg1:string):Promise<number>;
