// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppPath():Promise<string>;

export function GetDirectoryPath(arg1:number):Promise<string>;

export function GetRootFolder():Promise<string>;
