// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppPath() {
  return window['go']['main']['Getters']['GetAppPath']();
}

export function GetDirectoryFileCt(arg1) {
  return window['go']['main']['Getters']['GetDirectoryFileCt'](arg1);
}

export function GetDirectoryPath(arg1) {
  return window['go']['main']['Getters']['GetDirectoryPath'](arg1);
}

export function GetFileProperties(arg1) {
  return window['go']['main']['Getters']['GetFileProperties'](arg1);
}

export function GetRootFolder() {
  return window['go']['main']['Getters']['GetRootFolder']();
}
