// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckKeyFileInCWD() {
  return window['go']['main']['Getters']['CheckKeyFileInCWD']();
}

export function CheckRootFolderInCWD() {
  return window['go']['main']['Getters']['CheckRootFolderInCWD']();
}

export function FindEncryptedDuplicates(arg1) {
  return window['go']['main']['Getters']['FindEncryptedDuplicates'](arg1);
}

export function GetAppPath() {
  return window['go']['main']['Getters']['GetAppPath']();
}

export function GetDirName() {
  return window['go']['main']['Getters']['GetDirName']();
}

export function GetDirectoryFileCt(arg1) {
  return window['go']['main']['Getters']['GetDirectoryFileCt'](arg1);
}

export function GetDirectoryPath(arg1) {
  return window['go']['main']['Getters']['GetDirectoryPath'](arg1);
}

export function GetFileProperties(arg1) {
  return window['go']['main']['Getters']['GetFileProperties'](arg1);
}

export function GetFileTreePath(arg1, arg2) {
  return window['go']['main']['Getters']['GetFileTreePath'](arg1, arg2);
}

export function GetFilesByType(arg1, arg2) {
  return window['go']['main']['Getters']['GetFilesByType'](arg1, arg2);
}

export function GetFormattedAppDirSize() {
  return window['go']['main']['Getters']['GetFormattedAppDirSize']();
}

export function GetFormattedDirIndexSize(arg1) {
  return window['go']['main']['Getters']['GetFormattedDirIndexSize'](arg1);
}

export function GetFormattedDriveSize() {
  return window['go']['main']['Getters']['GetFormattedDriveSize']();
}

export function GetHeight() {
  return window['go']['main']['Getters']['GetHeight']();
}

export function GetLatestRelease() {
  return window['go']['main']['Getters']['GetLatestRelease']();
}

export function GetPercentOfDriveToDirSize(arg1) {
  return window['go']['main']['Getters']['GetPercentOfDriveToDirSize'](arg1);
}

export function GetRootDiskSpace() {
  return window['go']['main']['Getters']['GetRootDiskSpace']();
}

export function GetRootFolder() {
  return window['go']['main']['Getters']['GetRootFolder']();
}

export function GetTotalDirSize(arg1) {
  return window['go']['main']['Getters']['GetTotalDirSize'](arg1);
}
