// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAppPath():Promise<string>;

export function GetDirectoryFileCt(arg1:number):Promise<number>;

export function GetDirectoryPath(arg1:number):Promise<string>;

export function GetFileProperties(arg1:string):Promise<main.FileProperties>;

export function GetRootFolder():Promise<string>;
