// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LogMessage(arg1) {
  return window['go']['main']['Logger']['LogMessage'](arg1);
}
